#프로파일 설정
spring:
  profiles:
    active: dev #개발

#dev
---
spring:
  #db 세팅
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    driver-class-name: oracle.jdbc.OracleDriver
    username: BLUE
    password: 1234
  #스프링 시큐리티
  security:
    user: #스프링 시큐리티 기본 로그인 계정정보
      name: dev
      password: 1234
  config:
    activate:
      on-profile: dev
  thymeleaf:
    suffix: .html
    cache: false
    prefix: classpath:templates/
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#로깅설정
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

#서버
server:
  port: 80
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true


---
